version: '2'
services:
  api:
    build: .
    command: npm start
    volumes:
      - .:/app
      - /node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports: 
        - "3306:3306"
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mobqi