version: '2'

services:
  api:
    build: ./api
    command: npm run start-debug
    environment:
      - PORT=3000
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
      - "5858:5858"
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mobqi
      MYSQL_PASSWORD: root